export default [
    {
        id: 1,
        imageUrl: '../../assets/logo.png',
        name: 'John Doe Villa',
        location: 'Balikpapan',
        price: 'Rp 125.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi',
        availableDate: '2023-03-28'
    },
    {
        id: 2,
        imageUrl: '../../assets/logo.png',
        name: 'Jane Smith Villa',
        location: 'Jakarta',
        price: 'Rp 200.000',
        capacity: '4-6 People',
        amenities: 'Toilet, Free Wifi, Private Pool',
        availableDate: '2023-03-29'
    },
    {
        id: 3,
        imageUrl: '../../assets/logo.png',
        name: 'Bali Paradise Villa',
        location: 'Seminyak, Bali',
        price: 'Rp 350.000',
        capacity: '6-8 People',
        amenities: 'Toilet, Free Wifi, Private Beach Access',
        availableDate: '2023-03-30'
    },
    {
        id: 4,
        imageUrl: '../../assets/logo.png',
        name: 'Mountain View Chalet',
        location: 'Puncak, West Java',
        price: 'Rp 175.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, Fireplace',
    },
    {
        id: 5,
        imageUrl: '../../assets/logo.png',
        name: 'Lombok Seaside Bungalow',
        location: 'Senggigi, Lombok',
        price: 'Rp 220.000',
        capacity: '4-6 People',
        amenities: 'Toilet, Free Wifi, Swimming Pool',
    },
    {
        id: 6,
        imageUrl: '../../assets/logo.png',
        name: 'Kuta Beach Resort',
        location: 'Kuta, Bali',
        price: 'Rp 300.000',
        capacity: '6-8 People',
        amenities: 'Toilet, Free Wifi, Spa',
    },
    {
        id: 7,
        imageUrl: '../../assets/logo.png',
        name: 'Tropical Island Villa',
        location: 'Gili Trawangan, Lombok',
        price: 'Rp 400.000',
        capacity: '8-10 People',
        amenities: 'Toilet, Free Wifi, Private Beach',
    },
    {
        id: 8,
        imageUrl: '../../assets/logo.png',
        name: 'City View Apartment',
        location: 'Central Jakarta',
        price: 'Rp 150.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, Gym',
    },
    {
        id: 9,
        imageUrl: '../../assets/logo.png',
        name: 'Luxury Pool Villa',
        location: 'Nusa Dua, Bali',
        price: 'Rp 500.000',
        capacity: '8-10 People',
        amenities: 'Toilet, Free Wifi, Private Pool, Sea View',
    },
    {
        id: 10,
        imageUrl: '../../assets/logo.png',
        name: 'Cottage in the Woods',
        location: 'Bandung, West Java',
        price: 'Rp 200.000',
        capacity: '4-6 People',
        amenities: 'Toilet, Free Wifi, BBQ',
    },
    {
        id: 11,
        imageUrl: '../../assets/logo.png',
        name: 'Jogja Traditional House',
        location: 'Yogyakarta, Java',
        price: 'Rp 175.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, Garden',
    },
    {
        id: 12,
        imageUrl: '../../assets/logo.png',
        name: 'Surfing Beach House',
        location: 'Canggu, Bali',
        price: 'Rp 250.000',
        capacity: '4-6 People',
        amenities: 'Toilet, Free Wifi, Surfboards',
    },
    {
        id: 13,
        imageUrl: '../../assets/logo.png',
        name: 'Villa Puncak Panorama',
        location: 'Puncak, West Java',
        price: 'Rp 450.000',
        capacity: '8-10 People',
        amenities: 'Toilet, Free Wifi, Swimming Pool, Mountain View',
    },
    {
        id: 14,
        imageUrl: '../../assets/logo.png',
        name: 'Treehouse Retreat',
        location: 'Ubud, Bali',
        price: 'Rp 300.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, Jungle View',
    },
    {
        id: 15,
        imageUrl: '../../assets/logo.png',
        name: 'Villa Bukit Indah',
        location: 'Jimbaran, Bali',
        price: 'Rp 550.000',
        capacity: '8-10 People',
        amenities: 'Toilet, Free Wifi, Private Pool, Ocean View',
    },
    {
        id: 16,
        imageUrl: '../../assets/logo.png',
        name: 'Riverside Cabin',
        location: 'Sungai Liat, Bangka Belitung',
        price: 'Rp 175.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, Fishing',
    },
    {
        id: 17,
        imageUrl: '../../assets/logo.png',
        name: 'Tropical Retreat',
        location: 'Gili Air, Lombok',
        price: 'Rp 350.000',
        capacity: '6-8 People',
        amenities: 'Toilet, Free Wifi, Private Pool, Beach Access',
    },
    {
        id: 18,
        imageUrl: '../../assets/logo.png',
        name: 'Villa Tanjung Putus',
        location: 'Anyer, Banten',
        price: 'Rp 400.000',
        capacity: '8-10 People',
        amenities: 'Toilet, Free Wifi, Private Pool, Beachfront',
    },
    {
        id: 19,
        imageUrl: '../../assets/logo.png',
        name: 'City Center Apartment',
        location: 'Surabaya, East Java',
        price: 'Rp 250.000',
        capacity: '4-6 People',
        amenities: 'Toilet, Free Wifi, Gym, City View',
    },
    {
        id: 20,
        imageUrl: '../../assets/logo.png',
        name: 'Traditional Houseboat',
        location: 'Banjarmasin, South Kalimantan',
        price: 'Rp 300.000',
        capacity: '2-4 People',
        amenities: 'Toilet, Free Wifi, River View, Canoe',
    },
  ];